---
title: "DataSource"
output: html_document
date: "2023-03-03"
---

To run StormR functions users have to provide a tropical cyclone storm track dataset in which the location and some characteristics of storms are given across their lifespan.

StormR vient avec un jeu de test minimal basé sur le même format qu'IBTRACKS data provided by USA agencies [International Best Track Archive for Climate Stewardship](https://www.ncei.noaa.gov/products/international-best-track-archive) (Knapp et al., 2010). This database provides a fairly comprehensive record of worldwide tropical storms and cyclones with a 3-hours temporal resolution since 1841.

- Paramètres par défaut de StormR : pointent vers une extraction minimale de IBTRACKS_SP.

## Data sources
StormR a été développé pour utilisation principalement avec IBTACKS mais peut utiliser d'autres bases de données tant que les champs suivant sont fournis

To run StormR functions users have to provide a tropical cyclone storm track dataset in which the location and some characteristics of storms are given across their lifespan.  Other databases can be used as long as the following fields are provided:

| **Field name** | **Description** | **Example** | **Type** |
|:---|:---|:---:|:---:|
| $basin$ | Name of the area where the storm originated. Traditionally divided into seven basins: <br/>NA (North Atlantic)<br/>EP (Eastern North Pacific)<br/>WP (Western North Pacific)<br/>NI (North Indian)<br/>SI (South Indian)<br/>SP (Southern Pacific)<br/>SA (South Atlantic) | SP | Mandatory |
| $name$ | Name of the storm in capital letters | PAM | Mandatory |
| $seasons$ | Year of observation | 2015 | Mandatory |
| $isoTime$ | Date and time of observation (YYYY-MM-DD HH:mm:ss) | 13/03/2015 12:00 | Mandatory |
| $lon$ | Longitude of the observation (decimal degrees east) | 168.7 | Mandatory |
| $lat$ | Latitude of the observation (decimal degrees north) | -17.6 | Mandatory |
| $msw$* | Maximum sustained wind speed in knots ($kt$) | 150 | Mandatory |
| $sshs$* | Saffir-Simpson hurricane wind scale rating based on $msw$ (hre in $kt$):<br/>$-1 =$ tropical depression ($msw < 34$)<br/>$0 =$ tropical storm ($34 < msw < 64$), $1 =$ category 1 ($64 \le msw < 83$)<br/>$2 =$ Category 2 ($83 \le msw < 96$)<br/>$3 =$ Category 3 ($96 \le msw < 113$)<br/>$4 =$ Category 4 ($113 \le msw < 137$)<br/>$5 =$ Category 5 ($msw \ge 137$) | 5 | Recommended |
| $rmw$* | Radius of maximum winds, distance between the center of the storm and its band of strongest winds in nautical miles ($nm$) | 12 | Recommended |
| $pressure$* | Central pressure in millibar ($mb$) | 911 | Optional |
| $poci$* | Pressure of the last closed isobar in millibar ($mb$) | 922 | Optional |

*Units: before running the functions stormR converts nautical miles ($nm$) into kilometres ($km$), knots ($kt$) into meters per second ($m.s^{-1}$), and millibar ($mb$) into Pascal ($Pa$) 

## Download a Data Source
- Lien vers page téléchargement IBTraCKS
- Lien vers page téléchargement autre BDD 
- Code pour download


## Création d'un objet StormsDataset 
- iniDataBase sur les 2 BDD téléchargées
- différence de gestion IBTRACKS car paramètres par défaut vs autre bdd ou il faut redéfinir les champs.
- dire qu'on a déjà une BDD par défaut de test déjà existant (e.g. `?IBTRACKS_SP`), pas besoin de faire un `initDatabase`
- Gestion des unités ?

## Visualisation du contenu du StormDataset 
2-3 exemple :
- Structure de l'objet
- liste des noims disponibles dans la BDD
```
str(StormTestVanuatu)
unique(StormTestVanuatu@database$names))
```

## Reference
 * Knapp, K. R., Kruk, M. C., Levinson, D. H., Diamond, H. J., & Neumann, C. J. (2010). The International Best Track Archive for Climate Stewardship (IBTrACS). Bulletin of the American Meteorological Society, 91(3), Article 3. https://doi.org/10.1175/2009bams2755.1
