---
title: "Modeles"
output: html_document
date: "`r Sys.Date()`"
---

# Reconstruction des champs de vent d'un cyclone
Via les fonctions `SpatialBehaviour` et `TemporalBehaviour`, on utilise les modèmles paramétriques de reconstruciotn de stormrs, blabla...

## Wind field models

Using these data StormR computes radial wind speed $v_r$ (in $m.s^{-1}$) at the distance $r$ (in $km$) from the center of the storm using parametric models. Two widely used models developed by Holland (1980) and Willoughby et al. (2006) are available.

### Holland (1980)

$$
v_r = \sqrt{\frac{b}{\rho}\left(\frac{rmw}{r}\right)^b (poci - pc)e^{-\left(\frac{rmw}{r}\right)^b} + \left(\frac{rf}{2}\right)^2} - \left(\frac{rf}{2}\right)
$$

where <br />
$v_r$ is the radial wind speed (in $m.s^{-1}$) <br />
$r$ is the distance to the eye of the storm (in $km$) <br />
$msw$ is the maximum sustained wind speed (in $m.s^{-1}$) <br />
$rmw$ is the radius of maximum sustained wind speed (in $km$) <br />
$pc$ is the pressure at the center of the storm ($pressure$ in $mb$) <br />
$poci$ is the pressure at outermost closed isobar of the storm (in $mb$) <br />
$\rho = 1.15$ is the air density (in $kg.m^{-3}$) <br />
$f = 2 \times 7.29 \times10^{-5} \sin(\phi)$ is the Coriolis force (in $N.kg^{-1}$, with $\phi$ being the latitude) <br />
$b = \frac{\rho e \times msw^2}{poci - pc}$ is the shape parameter <br />

### Willoughby et al. (2006)

$$
\left\{
\begin{aligned}
v_r &= msw\left(\frac{r}{rmw}\right)^{n} \quad if \quad r < rmw \\
v_r &= msw\left((1-A)e^{-\frac{|r-rmw|}{X1}} + A e^{-\frac{|r-rmw|}{X2}}\right) \quad if \quad r \geq rmw \\
\end{aligned}
\right.
$$

where <br />
$v_r$ is the radial wind speed (in $m.s^{-1}$) <br />
$r$ is the distance to the eye of the storm (in $km$) <br />
$msw$ is the maximum sustained wind speed (in $m.s^{-1}$) <br />
$rmw$ is the radius of maximum sustained wind speed (in $km$) <br />
$X1 = 287.6 - 1.942msw + 7.799\ln(rmw) + 1.819|\phi|$<br />
$X2 = 25$ <br />
$n = 2.1340 + 0.0077msw - 0.4522\ln(rmw) - 0.0038|\phi|$<br />
$A = 0.5913 + 0.0029msw - 0.1361\ln(rmw) - 0.0042|\phi| (A\ge0)$<br />
$\phi$ is the latitude of the center of the storm 

Note that for both models if $rmw$ is not provided then it is approximated using an empirical formula derived from Willoughby et al. (2006)<br />
$rmw = 46.4e^{(-0.0155msw + 0.0169|\phi|)}$

## Asymmetry

The above models compute radial wind speeds that are symmetric around the center of the storm. However, winds are rarely symmetric around the center notably because of the translation movement of the storm (Yan and Zhang, 2022). It is therefore more realistic to add symmetry to the wind field generated by these models. For this we propose to use the model developed by Boose et al. (2001): <br />

$v_{r_{as}} = v_r - S(1-\sin(\alpha))\frac{v_h}{2}$

where <br />
$v_{r_{as}} \quad$ is the new radial wind speed with asymmetry $(m.s^{-1})$ <br />
$v_r \quad$ is the former radial wind speed without asymmetry $(m.s^{-1})$ <br />
$v_h \quad$ is the velocity of storm $(m.s^{-1})$ <br />
$S$ Asymmetry coefficient (usually set to 1) <br />
$\alpha \quad$ is tha angle between the storm direction and the point where $v_{r_{as}}$ is computed.
Clockwise in Nothern hemisphere, counterclokwise in Southern hemisphere. <br />

## Wind Direction
Wind direction $D$ (in degree) at each point is computed according to the following formula: <br />

$D = A_z - 90 - I \quad if \quad \phi > 0$ (North hemisphere)<br/>
$D = A_z + 90 + I \quad if \quad \phi < 0$ (South hemisphere)<br/>

where <br />
$A_z\quad$ is the azimuth from the point to the storm center <br/>
$I\quad$ is the cross isobar inflow angle which is either 20° on water or 40° on land <br/>
$\phi\quad$ is the latitude of the center of the storm 


## References
* Boose, E. R., Chamberlin, K. E., & Foster, D. R. (2001). Landscape and Regional Impacts of Hurricanes in New England. Ecological Monographs, 71(1), Article 1. https://doi.org/10.1890/0012-9615(2001)071[0027:LARIOH]2.0.CO;2
 
 * Holland, G. J. (1980). An Analytic Model of the Wind and Pressure Profiles in Hurricanes. Monthly Weather Review, 108(8), 1212–1218. https://doi.org/10.1175/1520-0493(1980)108<1212:AAMOTW>2.0.CO;2
 
* Willoughby, H. E., Darling, R. W. R., & Rahn, M. E. (2006). Parametric Representation of the Primary Hurricane Vortex. Part II: A New Family of Sectionally Continuous Profiles. Monthly Weather Review, 134(4), 1102–1120. https://doi.org/10.1175/MWR3106.1

* Yan, D., & Zhang, T. (2022). Research progress on tropical cyclone parametric wind field models and their application. Regional Studies in Marine Science, 51, 102207. https://doi.org/10.1016/j.rsma.2022.102207
