



test_that("Test checkInputsIDb function", {
  
  
  #Checking filename input
  expect_error(checkInputsIDb(fields = c("basin" = "basin",
                                         "names" = "name",
                                         "seasons" = "season",
                                         "isoTime" = "iso_time",
                                         "lon" = "usa_lon",
                                         "lat" = "usa_lat",
                                         "msw" = "usa_wind",
                                         "sshs" = "usa_sshs",
                                         "rmw" = "usa_rmw",
                                         "pressure" = "usa_pres",
                                         "poci" = "usa_poci"),
                              basin = "SP",
                              unit_conversion = c(msw = "knt_to_ms",
                                                  rmw = "nm_to_km",
                                                  pressure="mb_to_pa",
                                                  poci="mb_to_pa"),
                              verbose = TRUE))
  
  expect_error(checkInputsIDb(filename = 1,
                              fields = c("basin" = "basin",
                                         "names" = "name",
                                         "seasons" = "season",
                                         "isoTime" = "iso_time",
                                         "lon" = "usa_lon",
                                         "lat" = "usa_lat",
                                         "msw" = "usa_wind",
                                         "sshs" = "usa_sshs",
                                         "rmw" = "usa_rmw",
                                         "pressure" = "usa_pres",
                                         "poci" = "usa_poci"),
                              basin = "SP",
                              unit_conversion = c(msw = "knt_to_ms",
                                                  rmw = "nm_to_km",
                                                  pressure="mb_to_pa",
                                                  poci="mb_to_pa"),
                              verbose = TRUE))
  
  expect_error(checkInputsIDb(filename = T,
                              fields = c("basin" = "basin",
                                         "names" = "name",
                                         "seasons" = "season",
                                         "isoTime" = "iso_time",
                                         "lon" = "usa_lon",
                                         "lat" = "usa_lat",
                                         "msw" = "usa_wind",
                                         "sshs" = "usa_sshs",
                                         "rmw" = "usa_rmw",
                                         "pressure" = "usa_pres",
                                         "poci" = "usa_poci"),
                              basin = "SP",
                              unit_conversion = c(msw = "knt_to_ms",
                                                  rmw = "nm_to_km",
                                                  pressure="mb_to_pa",
                                                  poci="mb_to_pa"),
                              verbose = TRUE))
  
  
  expect_error(checkInputsIDb(filename = c("data", ".nc"),
                              fields = c("basin" = "basin",
                                         "names" = "name",
                                         "seasons" = "season",
                                         "isoTime" = "iso_time",
                                         "lon" = "usa_lon",
                                         "lat" = "usa_lat",
                                         "msw" = "usa_wind",
                                         "sshs" = "usa_sshs",
                                         "rmw" = "usa_rmw",
                                         "pressure" = "usa_pres",
                                         "poci" = "usa_poci"),
                              basin = "SP",
                              unit_conversion = c(msw = "knt_to_ms",
                                                  rmw = "nm_to_km",
                                                  pressure="mb_to_pa",
                                                  poci="mb_to_pa"),
                              verbose = TRUE))
  
  #Checking fields input
  expect_error(checkInputsIDb(filename = "database.nc",
                              fields =  1,
                              basin = "SP",
                              unit_conversion = c(msw = "knt_to_ms",
                                                  rmw = "nm_to_km",
                                                  pressure="mb_to_pa",
                                                  poci="mb_to_pa"),
                              verbose = TRUE))
  
  expect_error(checkInputsIDb(filename = "database.nc",
                              fields = T,
                              basin = "SP",
                              unit_conversion = c(msw = "knt_to_ms",
                                                  rmw = "nm_to_km",
                                                  pressure="mb_to_pa",
                                                  poci="mb_to_pa"),
                              verbose = TRUE))
  
  expect_error(checkInputsIDb(filename = "database.nc",
                              fields = c("basin" = "basin",
                                         "seasons" = "season",
                                         "isoTime" = "iso_time",
                                         "lon" = "usa_lon",
                                         "lat" = "usa_lat",
                                         "msw" = "usa_wind",
                                         "sshs" = "usa_sshs",
                                         "rmw" = "usa_rmw",
                                         "pressure" = "usa_pres",
                                         "poci" = "usa_poci"),
                              basin = "SP",
                              unit_conversion = c(msw = "knt_to_ms",
                                                  rmw = "nm_to_km",
                                                  pressure="mb_to_pa",
                                                  poci="mb_to_pa"),
                              verbose = TRUE))
  
  expect_error(checkInputsIDb(filename = "database.nc",
                              fields = c("basin" = "basin",
                                         "names" = "name",
                                         "isoTime" = "iso_time",
                                         "lon" = "usa_lon",
                                         "lat" = "usa_lat",
                                         "msw" = "usa_wind",
                                         "sshs" = "usa_sshs",
                                         "rmw" = "usa_rmw",
                                         "pressure" = "usa_pres",
                                         "poci" = "usa_poci"),
                              basin = "SP",
                              unit_conversion = c(msw = "knt_to_ms",
                                                  rmw = "nm_to_km",
                                                  pressure="mb_to_pa",
                                                  poci="mb_to_pa"),
                              verbose = TRUE))
  
  expect_error(checkInputsIDb(filename = "database.nc",
                              fields = c("basin" = "basin",
                                         "names" = "name",
                                         "seasons" = "season",
                                         "lon" = "usa_lon",
                                         "lat" = "usa_lat",
                                         "msw" = "usa_wind",
                                         "sshs" = "usa_sshs",
                                         "rmw" = "usa_rmw",
                                         "pressure" = "usa_pres",
                                         "poci" = "usa_poci"),
                              basin = "SP",
                              unit_conversion = c(msw = "knt_to_ms",
                                                  rmw = "nm_to_km",
                                                  pressure="mb_to_pa",
                                                  poci="mb_to_pa"),
                              verbose = TRUE))
  
  expect_error(checkInputsIDb(filename = "database.nc",
                              fields = c("basin" = "basin",
                                         "names" = "name",
                                         "seasons" = "season",
                                         "isoTime" = "iso_time",
                                         "lat" = "usa_lat",
                                         "msw" = "usa_wind",
                                         "sshs" = "usa_sshs",
                                         "rmw" = "usa_rmw",
                                         "pressure" = "usa_pres",
                                         "poci" = "usa_poci"),
                              basin = "SP",
                              unit_conversion = c(msw = "knt_to_ms",
                                                  rmw = "nm_to_km",
                                                  pressure="mb_to_pa",
                                                  poci="mb_to_pa"),
                              verbose = TRUE))
  
  expect_error(checkInputsIDb(filename = "database.nc",
                              fields = c("basin" = "basin",
                                         "names" = "name",
                                         "seasons" = "season",
                                         "isoTime" = "iso_time",
                                         "lon" = "usa_lon",
                                         "msw" = "usa_wind",
                                         "sshs" = "usa_sshs",
                                         "rmw" = "usa_rmw",
                                         "pressure" = "usa_pres",
                                         "poci" = "usa_poci"),
                              basin = "SP",
                              unit_conversion = c(msw = "knt_to_ms",
                                                  rmw = "nm_to_km",
                                                  pressure="mb_to_pa",
                                                  poci="mb_to_pa"),
                              verbose = TRUE))
  
  
  expect_error(checkInputsIDb(filename = "database.nc",
                              fields = c("basin" = "basin",
                                         "names" = "name",
                                         "seasons" = "season",
                                         "isoTime" = "iso_time",
                                         "lon" = "usa_lon",
                                         "lat" = "usa_lat",
                                         "sshs" = "usa_sshs",
                                         "rmw" = "usa_rmw",
                                         "pressure" = "usa_pres",
                                         "poci" = "usa_poci"),
                              basin = "SP",
                              unit_conversion = c(msw = "knt_to_ms",
                                                  rmw = "nm_to_km",
                                                  pressure="mb_to_pa",
                                                  poci="mb_to_pa"),
                              verbose = TRUE))
  
  expect_error(checkInputsIDb(filename = "database.nc",
                              fields = c("basin" = "basin",
                                         "names" = "name",
                                         "seasons" = "season",
                                         "isoTime" = "iso_time",
                                         "lon" = "usa_lon",
                                         "lat" = "usa_lat",
                                         "msw" = "usa_wind",
                                         "sshs" = "usa_sshs",
                                         "rmw" = "usa_rmw",
                                         "pressure" = "usa_pres",
                                         "poci" = "usa_poci"),
                              basin = "SP",
                              unit_conversion = c(rmw = "nm_to_km",
                                                  pressure="mb_to_pa",
                                                  poci="mb_to_pa"),
                              verbose = TRUE))
  
  expect_error(checkInputsIDb(filename = "database.nc",
                              fields = c("basin" = "basin",
                                         "names" = "name",
                                         "seasons" = "season",
                                         "isoTime" = "iso_time",
                                         "lon" = "usa_lon",
                                         "lat" = "usa_lat",
                                         "msw" = "usa_wind",
                                         "sshs" = "usa_sshs",
                                         "rmw" = "usa_rmw",
                                         "pressure" = "usa_pres",
                                         "poci" = "usa_poci"),
                              basin = "SP",
                              unit_conversion = c(msw = "knt2ms",
                                                  rmw = "nm_to_km",
                                                  pressure="mb_to_pa",
                                                  poci="mb_to_pa"),
                              verbose = TRUE))
  
  expect_error(checkInputsIDb(filename = "database.nc",
                              fields = c("basin" = "basin",
                                         "names" = "name",
                                         "seasons" = "season",
                                         "isoTime" = "iso_time",
                                         "lon" = "usa_lon",
                                         "lat" = "usa_lat",
                                         "msw" = "usa_wind",
                                         "sshs" = "usa_sshs",
                                         "rmw" = "usa_rmw",
                                         "pressure" = "usa_pres",
                                         "poci" = "usa_poci"),
                              basin = "SP",
                              unit_conversion = c(msw = "knt_to_ms",
                                                  pressure="mb_to_pa",
                                                  poci="mb_to_pa"),
                              verbose = TRUE))
  
  expect_error(checkInputsIDb(filename = "database.nc",
                              fields = c("basin" = "basin",
                                         "names" = "name",
                                         "seasons" = "season",
                                         "isoTime" = "iso_time",
                                         "lon" = "usa_lon",
                                         "lat" = "usa_lat",
                                         "msw" = "usa_wind",
                                         "sshs" = "usa_sshs",
                                         "rmw" = "usa_rmw",
                                         "pressure" = "usa_pres",
                                         "poci" = "usa_poci"),
                              basin = "SP",
                              unit_conversion = c(msw = "knt_to_ms",
                                                  rmw = "nm2km",
                                                  pressure="mb_to_pa",
                                                  poci="mb_to_pa"),
                              verbose = TRUE))
  
  expect_error(checkInputsIDb(filename = "database.nc",
                              fields = c("basin" = "basin",
                                         "names" = "name",
                                         "seasons" = "season",
                                         "isoTime" = "iso_time",
                                         "lon" = "usa_lon",
                                         "lat" = "usa_lat",
                                         "msw" = "usa_wind",
                                         "sshs" = "usa_sshs",
                                         "rmw" = "usa_rmw",
                                         "pressure" = "usa_pres",
                                         "poci" = "usa_poci"),
                              basin = "SP",
                              unit_conversion = c(msw = "knt_to_ms",
                                                  rmw = "nm_to_km",
                                                  poci="mb_to_pa"),
                              verbose = TRUE))
  
  expect_error(checkInputsIDb(filename = "database.nc",
                              fields = c("basin" = "basin",
                                         "names" = "name",
                                         "seasons" = "season",
                                         "isoTime" = "iso_time",
                                         "lon" = "usa_lon",
                                         "lat" = "usa_lat",
                                         "msw" = "usa_wind",
                                         "sshs" = "usa_sshs",
                                         "rmw" = "usa_rmw",
                                         "pressure" = "usa_pres",
                                         "poci" = "usa_poci"),
                              basin = "SP",
                              unit_conversion = c(msw = "knt_to_ms",
                                                  rmw = "nm_to_km",
                                                  pressure="mb2pa",
                                                  poci="mb_to_pa"),
                              verbose = TRUE))
  
  expect_error(checkInputsIDb(filename = "database.nc",
                              fields = c("basin" = "basin",
                                         "names" = "name",
                                         "seasons" = "season",
                                         "isoTime" = "iso_time",
                                         "lon" = "usa_lon",
                                         "lat" = "usa_lat",
                                         "msw" = "usa_wind",
                                         "sshs" = "usa_sshs",
                                         "rmw" = "usa_rmw",
                                         "pressure" = "usa_pres",
                                         "poci" = "usa_poci"),
                              basin = "SP",
                              unit_conversion = c(msw = "knt_to_ms",
                                                  rmw = "nm_to_km",
                                                  pressure = "mb_to_pa"),
                              verbose = TRUE))
  
  expect_error(checkInputsIDb(filename = "database.nc",
                              fields = c("basin" = "basin",
                                         "names" = "name",
                                         "seasons" = "season",
                                         "isoTime" = "iso_time",
                                         "lon" = "usa_lon",
                                         "lat" = "usa_lat",
                                         "msw" = "usa_wind",
                                         "sshs" = "usa_sshs",
                                         "rmw" = "usa_rmw",
                                         "pressure" = "usa_pres",
                                         "poci" = "usa_poci"),
                              basin = "SP",
                              unit_conversion = c(msw = "knt_to_ms",
                                                  rmw = "nm_to_km",
                                                  pressure = "mb_to_pa",
                                                  poci = "mb2pa"),
                              verbose = TRUE))
  
  #Checking basin input
  expect_error(checkInputsIDb(filename = "database.nc",
                              fields = c("basin" = "basin",
                                         "names" = "name",
                                         "seasons" = "season",
                                         "isoTime" = "iso_time",
                                         "lon" = "usa_lon",
                                         "lat" = "usa_lat",
                                         "msw" = "usa_wind",
                                         "sshs" = "usa_sshs",
                                         "rmw" = "usa_rmw",
                                         "pressure" = "usa_pres",
                                         "poci" = "usa_poci"),
                              basin = 1,
                              unit_conversion = c(msw = "knt_to_ms",
                                                  rmw = "nm_to_km",
                                                  pressure = "mb_to_pa",
                                                  poci = "mb_to_pa"),
                              verbose = TRUE))
  
  expect_error(checkInputsIDb(filename = "database.nc",
                              fields = c("basin" = "basin",
                                         "names" = "name",
                                         "seasons" = "season",
                                         "isoTime" = "iso_time",
                                         "lon" = "usa_lon",
                                         "lat" = "usa_lat",
                                         "msw" = "usa_wind",
                                         "sshs" = "usa_sshs",
                                         "rmw" = "usa_rmw",
                                         "pressure" = "usa_pres",
                                         "poci" = "usa_poci"),
                              basin = T,
                              unit_conversion = c(msw = "knt_to_ms",
                                                  rmw = "nm_to_km",
                                                  pressure = "mb_to_pa",
                                                  poci = "mb_to_pa"),
                              verbose = TRUE))
  
  expect_error(checkInputsIDb(filename = "database.nc",
                              fields = c("basin" = "basin",
                                         "names" = "name",
                                         "seasons" = "season",
                                         "isoTime" = "iso_time",
                                         "lon" = "usa_lon",
                                         "lat" = "usa_lat",
                                         "msw" = "usa_wind",
                                         "sshs" = "usa_sshs",
                                         "rmw" = "usa_rmw",
                                         "pressure" = "usa_pres",
                                         "poci" = "usa_poci"),
                              basin = c("NA", "WP"),
                              unit_conversion = c(msw = "knt_to_ms",
                                                  rmw = "nm_to_km",
                                                  pressure = "mb_to_pa",
                                                  poci = "mb_to_pa"),
                              verbose = TRUE))
  
  #Checking unit_conversion input
  expect_error(checkInputsIDb(filename = "database.nc",
                              fields = c("basin" = "basin",
                                         "names" = "name",
                                         "seasons" = "season",
                                         "isoTime" = "iso_time",
                                         "lon" = "usa_lon",
                                         "lat" = "usa_lat",
                                         "msw" = "usa_wind",
                                         "sshs" = "usa_sshs",
                                         "rmw" = "usa_rmw",
                                         "pressure" = "usa_pres",
                                         "poci" = "usa_poci"),
                              basin = "SP",
                              unit_conversion = 1,
                              verbose = TRUE))
  
  expect_error(checkInputsIDb(filename = "database.nc",
                              fields = c("basin" = "basin",
                                         "names" = "name",
                                         "seasons" = "season",
                                         "isoTime" = "iso_time",
                                         "lon" = "usa_lon",
                                         "lat" = "usa_lat",
                                         "msw" = "usa_wind",
                                         "sshs" = "usa_sshs",
                                         "rmw" = "usa_rmw",
                                         "pressure" = "usa_pres",
                                         "poci" = "usa_poci"),
                              basin = "SP",
                              unit_conversion = T,
                              verbose = TRUE))
  
  
  #Checking verbose input
  expect_error(checkInputsIDb(filename = "database.nc",
                              fields = c("basin" = "basin",
                                         "names" = "name",
                                         "seasons" = "season",
                                         "isoTime" = "iso_time",
                                         "lon" = "usa_lon",
                                         "lat" = "usa_lat",
                                         "msw" = "usa_wind",
                                         "sshs" = "usa_sshs",
                                         "rmw" = "usa_rmw",
                                         "pressure" = "usa_pres",
                                         "poci" = "usa_poci"),
                              basin = 1,
                              unit_conversion = c(msw = "knt_to_ms",
                                                  rmw = "nm_to_km",
                                                  pressure = "mb_to_pa",
                                                  poci = "mb_to_pa"),
                              verbose = 1))
  
  expect_error(checkInputsIDb(filename = "database.nc",
                              fields = c("basin" = "basin",
                                         "names" = "name",
                                         "seasons" = "season",
                                         "isoTime" = "iso_time",
                                         "lon" = "usa_lon",
                                         "lat" = "usa_lat",
                                         "msw" = "usa_wind",
                                         "sshs" = "usa_sshs",
                                         "rmw" = "usa_rmw",
                                         "pressure" = "usa_pres",
                                         "poci" = "usa_poci"),
                              basin = 1,
                              unit_conversion = c(msw = "knt_to_ms",
                                                  rmw = "nm_to_km",
                                                  pressure = "mb_to_pa",
                                                  poci = "mb_to_pa"),
                              verbose = "1"))

})
