# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

computeAsymmetry_cpp <- function(asymmetry, wind, x, y, vx, vy, vh, r, rmw, lat) {
    .Call(`_StormR_computeAsymmetry_cpp`, asymmetry, wind, x, y, vx, vy, vh, r, rmw, lat)
}

willoughby_cpp <- function(r, rmw, msw, lat) {
    .Call(`_StormR_willoughby_cpp`, r, rmw, msw, lat)
}

